[workspace]
members = [
    "contracts/energy-token",
    "contracts/marketplace",
    "contracts/network-incentives",
]
resolver = "2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
panic = "abort"
lto = true
codegen-units = 1
