[package]
name = "marketplace"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/contract.rs"
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "22.0.2"

[dev-dependencies]
soroban-sdk = { version = "22.0.2", features = ["testutils"] }
